### ISSUE TITLE
how to run it in ros

### ISSUE THREAD

**Issue by zhang-mu-zhi** [reiniscimurs/GDAM#11]
I want to run the algorithm in ross but this algorithm is not packaged so I wonder how to proceed

I'm trying to make a package file myself and proceed, but I'm wondering if there's a better way.

**Comment by reiniscimurs** [comment]
Hi,
This algorithm does not require packaging and can be run as is as a python executable, given that there is a trained model and the dependencies are met. I have no experience running it in other ways so I could not help you there.

**Comment by zhang-mu-zhi** [comment]
> 您好， 该算法不需要打包，并且可以作为 python 可执行文件运行，前提是有经过训练的模型并且满足依赖关系。我没有以其他方式运行它的经验，所以我无法帮助你。

**Comment by zhang-mu-zhi** [comment]
> 您好， 该算法不需要打包，并且可以作为 python 可执行文件运行，前提是有经过训练的模型并且满足依赖关系。我没有以其他方式运行它的经验，所以我无法帮助你。

**Comment by zhang-mu-zhi** [comment]
> Hi, This algorithm does not require packaging and can be run as is as a python executable, given that there is a trained model and the dependencies are met. I have no experience running it in other ways so I could not help you there.



sorry.
The code has a ROS part.
I haven't seen that before.

Please close this issue
